apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-zqlk08
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-zqlk08
  namespace: my-nginx-zqlk08
  labels:
    name: nginx-zqlk08
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-zqlk08
  template:
    metadata:
      namespace: my-nginx-zqlk08
      labels:
        name: nginx-zqlk08
    spec:
      containers:
      - name: nginx-zqlk08
        image: nginx
        ports:
        - containerPort: 80

